### ISSUE TITLE
Need to specify --configuration and --framework parameters when calling dotnet publish

### ISSUE THREAD

**Issue by ivankahl** [tsibelman/serverless-multi-dotnet#4]
I am trying to use this plugin to build multiple projects in a serverless project, but everytime I try and deploy it I get either of the errors:

```
Missing required parameter: --configuration 
```
or
```
Missing required parameter: --framework
```

I can try my hand at fixing it if this is a legitimate issue.

**Comment by tsibelman** [comment]
Interesting what version of dotnet lambda tool are you using in your project ?

**Comment by ivankahl** [comment]
Versions are as follows:

```
> dotnet --version
3.0.100
> serverless --version
Framework Core: 1.54.0 
Plugin: 3.1.2
SDK: 2.1.1 
Components Core: 1.1.1  
Components CLI: 1.2.3 
> aws --version
aws-cli/1.16.231 Python/3.6.0 Windows/10 botocore/1.12.221
```

My projects are all targeting the _dotnetcore2.1_ runtime.  Is it possible the issue has got something to do with .NET 3?

**Comment by tsibelman** [comment]
This plugin is relying on having DotNetCliToolReference for Amazon.Lambda.Tools defenid in the project file like this

```
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.2.0" />
  </ItemGroup>

```
Do you have it in your project ?

**Comment by ivankahl** [comment]
I do have have that.  Also version 2.2.0

**Comment by tsibelman** [comment]
If you can add a small project that has this issue and a cli command you using I can try to debug it
